/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cartridges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 cartridges */
        get: operations["get-api-v1-cartridges"];
        put?: never;
        /** Post API v1 cartridges */
        post: operations["post-api-v1-cartridges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cartridges/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 cartridges logs */
        get: operations["get-api-v1-cartridges-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cartridges/refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 cartridges refill */
        post: operations["post-api-v1-cartridges-refill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cartridges/refill-printer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 cartridges refill printer */
        post: operations["post-api-v1-cartridges-refill-printer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cartridges/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 cartridges replace */
        post: operations["post-api-v1-cartridges-replace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cartridges/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 cartridges stock */
        post: operations["post-api-v1-cartridges-stock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cartridges/stock/refill-bottles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 cartridges stock refill bottles */
        post: operations["post-api-v1-cartridges-stock-refill-bottles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/discovery/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 discovery probe */
        post: operations["post-api-v1-discovery-probe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 health */
        get: operations["get-api-v1-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 health live */
        get: operations["get-api-v1-health-live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 health ready */
        get: operations["get-api-v1-health-ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 jobs by ID */
        get: operations["get-api-v1-jobs-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 printers */
        get: operations["get-api-v1-printers"];
        put?: never;
        /** Post API v1 printers */
        post: operations["post-api-v1-printers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 printers register */
        post: operations["post-api-v1-printers-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 printers by ID */
        get: operations["get-api-v1-printers-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 printers by ID counters */
        get: operations["get-api-v1-printers-by-id-counters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 printers by ID credentials */
        post: operations["post-api-v1-printers-by-id-credentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 printers by ID endpoints */
        post: operations["post-api-v1-printers-by-id-endpoints"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API v1 printers by ID poll */
        post: operations["post-api-v1-printers-by-id-poll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}/polling-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 printers by ID polling runs */
        get: operations["get-api-v1-printers-by-id-polling-runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/printers/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 printers by ID usage */
        get: operations["get-api-v1-printers-by-id-usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snmp/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API v1 snmp profiles */
        get: operations["get-api-v1-snmp-profiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActionOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ActionOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            counter: number;
            /** @enum {string} */
            counter_quality: "valid" | "unverified" | "unsupported" | "unavailable" | "suspicious";
            message: string;
            status: string;
        };
        AddRefillBottlesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AddRefillBottlesInputBody.json
             */
            readonly $schema?: string;
            cartridge_id: string;
            notes?: string;
            /** Format: int64 */
            quantity: number;
        };
        Cartridge: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Cartridge.json
             */
            readonly $schema?: string;
            compatible_models?: string;
            id: string;
            name: string;
            sku_code: string;
            /** Format: int64 */
            stock_empty: number;
            /** Format: int64 */
            stock_new: number;
            /** Format: int64 */
            stock_refill_bottles: number;
            /** Format: int64 */
            stock_refilled: number;
        };
        CartridgeListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CartridgeListOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["Cartridge"][] | null;
            /** Format: int64 */
            total: number;
        };
        CartridgeLog: {
            action_type: string;
            cartridge_id: string;
            counter_collected_at?: string;
            counter_quality?: string;
            device_id?: string;
            id: string;
            notes?: string;
            /** Format: int64 */
            page_count?: number;
            performed_at: string;
            /** Format: int64 */
            printed_pages?: number;
            /** Format: int64 */
            quantity: number;
            source_type?: string;
        };
        Counter: {
            /** Format: date-time */
            collected_at: string;
            definition_key: string;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            quality: "valid" | "unverified" | "unsupported" | "unavailable" | "suspicious";
            /** Format: int64 */
            raw_value: number;
            scope: string;
            /** @enum {string} */
            unit: "impressions" | "sheets";
        };
        CounterPageOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CounterPageOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["Counter"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        CreateCartridgeInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateCartridgeInputBody.json
             */
            readonly $schema?: string;
            compatible_models?: string;
            name: string;
            sku_code: string;
            /** Format: int64 */
            stock_empty?: number;
            /** Format: int64 */
            stock_new?: number;
            /** Format: int64 */
            stock_refill_bottles?: number;
            /** Format: int64 */
            stock_refilled?: number;
        };
        CreatePrinterInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreatePrinterInputBody.json
             */
            readonly $schema?: string;
            asset_code?: string;
            department?: string;
            display_name: string;
            manufacturer?: string;
            model?: string;
            serial?: string;
            sys_object_id?: string;
        };
        CredentialInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CredentialInputBody.json
             */
            readonly $schema?: string;
            auth_passphrase?: string;
            /** @enum {string} */
            auth_protocol?: "MD5" | "SHA";
            community?: string;
            priv_passphrase?: string;
            /** @enum {string} */
            priv_protocol?: "DES" | "AES" | "AES128";
            username?: string;
            /** @enum {string} */
            version: "2c" | "3";
        };
        CredentialOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CredentialOutputBody.json
             */
            readonly $schema?: string;
            id: string;
            /** @enum {string} */
            version: "2c" | "3";
        };
        DailyUsage: {
            definition_key: string;
            /** Format: int64 */
            delta: number;
            /** Format: date */
            local_date: string;
            /** @enum {string} */
            quality: "valid" | "unverified";
            scope: string;
            /** @enum {string} */
            unit: "impressions" | "sheets";
        };
        DiscoveryInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DiscoveryInputBody.json
             */
            readonly $schema?: string;
            /** Format: ipv4 */
            address: string;
            auth_passphrase?: string;
            /** @enum {string} */
            auth_protocol?: "MD5" | "SHA";
            community?: string;
            /**
             * Format: int64
             * @default 161
             */
            port: number;
            priv_passphrase?: string;
            /** @enum {string} */
            priv_protocol?: "DES" | "AES" | "AES128";
            /**
             * Format: int64
             * @default 3
             */
            timeout: number;
            username?: string;
            /** @enum {string} */
            version: "2c" | "3";
        };
        DiscoveryMarker: {
            /** Format: int64 */
            counter_unit: number;
            instance: string;
            /** Format: int64 */
            life_count: number;
        };
        DiscoveryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DiscoveryOutputBody.json
             */
            readonly $schema?: string;
            /** Format: ipv4 */
            address: string;
            description: string;
            markers?: components["schemas"]["DiscoveryMarker"][] | null;
            name: string;
            serial: string;
            sys_object_id: string;
        };
        EndpointInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EndpointInputBody.json
             */
            readonly $schema?: string;
            address: string;
            credential_id?: string;
            /** @default false */
            is_primary: boolean;
            /**
             * Format: int64
             * @default 161
             */
            port: number;
            /**
             * @default snmp
             * @enum {string}
             */
            protocol: "snmp";
        };
        EndpointOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EndpointOutputBody.json
             */
            readonly $schema?: string;
            address: string;
            credential_id?: string;
            device_id: string;
            id: string;
            is_primary: boolean;
            /** Format: int64 */
            port: number;
            /** @constant */
            protocol: "snmp";
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /** @constant */
            status: "ok";
            /** Format: date-time */
            time: string;
        };
        JobAcceptedOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/JobAcceptedOutputBody.json
             */
            readonly $schema?: string;
            job_id: string;
            /** @constant */
            status: "queued";
            status_url: string;
        };
        JobOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/JobOutputBody.json
             */
            readonly $schema?: string;
            device_id: string;
            error_code?: string;
            id: string;
            /** @enum {string} */
            status: "queued" | "success" | "failed";
        };
        LogsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LogsOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["CartridgeLog"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PollingRun: {
            /** Format: int64 */
            attempt_count: number;
            /** Format: date-time */
            ended_at?: string;
            error_code?: string;
            id: string;
            job_kind: string;
            /** Format: int64 */
            profile_version?: number;
            /** @enum {string} */
            result: "running" | "success" | "failed";
            /** Format: date-time */
            started_at: string;
        };
        PollingRunPageOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PollingRunPageOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["PollingRun"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        Printer: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Printer.json
             */
            readonly $schema?: string;
            asset_code?: string;
            department?: string;
            display_name: string;
            id: string;
            /** Format: date-time */
            last_seen_at?: string;
            manufacturer?: string;
            model?: string;
            serial?: string;
            /** @enum {string} */
            status: "online" | "offline" | "unknown" | "unavailable";
        };
        PrinterPageOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PrinterPageOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["Printer"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        Profile: {
            counter_keys: string[] | null;
            id: string;
            manufacturer: string;
            /** @enum {string} */
            verification_status: "verified" | "unverified" | "experimental";
            /** Format: int64 */
            version: number;
        };
        ProfileListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProfileListOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["Profile"][] | null;
            /** Format: int64 */
            total: number;
        };
        RefillCartridgesInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RefillCartridgesInputBody.json
             */
            readonly $schema?: string;
            cartridge_id: string;
            notes?: string;
            /** Format: int64 */
            quantity: number;
        };
        RefillPrinterInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RefillPrinterInputBody.json
             */
            readonly $schema?: string;
            cartridge_id: string;
            device_id: string;
            notes?: string;
            /** Format: int64 */
            page_count?: number;
            /** Format: int64 */
            quantity: number;
        };
        RegisterPrinterInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RegisterPrinterInputBody.json
             */
            readonly $schema?: string;
            address: string;
            asset_code?: string;
            auth_passphrase?: string;
            /** @enum {string} */
            auth_protocol?: "MD5" | "SHA";
            community?: string;
            department?: string;
            display_name: string;
            manufacturer?: string;
            model?: string;
            /**
             * Format: int64
             * @default 161
             */
            port: number;
            priv_passphrase?: string;
            /** @enum {string} */
            priv_protocol?: "DES" | "AES" | "AES128";
            profile_id?: string;
            serial?: string;
            sys_object_id?: string;
            username?: string;
            /** @enum {string} */
            version: "2c" | "3";
        };
        RegistrationOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RegistrationOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            counter_definition_count: number;
            credential_id: string;
            endpoint_id: string;
            poll_job_id?: string;
            /** @enum {string} */
            poll_status: "queued" | "not_started";
            printer: components["schemas"]["Printer"];
            profile_id?: string;
        };
        ReplaceCartridgeInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReplaceCartridgeInputBody.json
             */
            readonly $schema?: string;
            cartridge_id: string;
            device_id: string;
            notes?: string;
            /** Format: int64 */
            page_count?: number;
            /** @enum {string} */
            source_type: "new" | "refilled";
        };
        StatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/StatusOutputBody.json
             */
            readonly $schema?: string;
            message?: string;
            status: string;
        };
        UpdateStockInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateStockInputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            add_stock_empty?: number;
            /** Format: int64 */
            add_stock_new?: number;
            /** Format: int64 */
            add_stock_refilled?: number;
            cartridge_id: string;
            notes?: string;
        };
        UsagePageOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UsagePageOutputBody.json
             */
            readonly $schema?: string;
            data: components["schemas"]["DailyUsage"][] | null;
            timezone: string;
            /** Format: int64 */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-api-v1-cartridges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartridgeListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-cartridges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCartridgeInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cartridge"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-cartridges-logs": {
        parameters: {
            query?: {
                cartridge_id?: string;
                device_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-cartridges-refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefillCartridgesInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-cartridges-refill-printer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefillPrinterInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-cartridges-replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceCartridgeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-cartridges-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStockInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-cartridges-stock-refill-bottles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRefillBottlesInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-discovery-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-health-live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-health-ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-jobs-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-printers": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterPageOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-printers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrinterInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Printer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-printers-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPrinterInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-printers-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Printer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-printers-by-id-counters": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterPageOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-printers-by-id-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-printers-by-id-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndpointInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-v1-printers-by-id-poll": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAcceptedOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-printers-by-id-polling-runs": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollingRunPageOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-printers-by-id-usage": {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                timezone?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsagePageOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-v1-snmp-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
